In [4]:
import numpy as np
import torch

ModuleNotFoundError: No module named 'torch'

## Numpy
### 1D Array with Numpy

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [4]:
print('Rank of t:', t.ndim)
print('Shape of t:', t.shape)

Rank of t: 1
Shape of t: (7,)


In [6]:
print('t[0] t[1] t[-1] =', t[0], t[1], t[-1])
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1])
print('t[:2] t[3:]     = ', t[:2], t[3:])

t[0] t[1] t[-1] = 0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


### 2D Array with Numpy

In [10]:
t = np.array([[1., 2., 3.,], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [12]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  2
Shape of t:  (4, 3)


In [30]:
print(t[0], t[1], t[-1])
print(t[0:4])

[1. 2. 3.] [4. 5. 6.] [10. 11. 12.]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


## Pytorch Tensor
### 1D Array with Pytorch

In [31]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [32]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2D Array with Pytorch

In [6]:
import torch

t = torch.FloatTensor([[1., 2., 3.],
                      [4., 5., 6.],
                      [7., 8., 9.],
                      [10., 11., 12.]
                      ])
print(t)
print(t.dim())
print(t.size())

ModuleNotFoundError: No module named 'torch'

In [3]:
print(t[:, 1]) # 모든 행에서, 두번째 열
print(t[:, 1].size())
print(t[:, 1].dim())
print(t[:, :-1])
print('-----------------------')
print(t[1:, 2:]) # 1번부터 끝행까지 중, 2번부터 끝열까지
print(t[1:, 2:].size()) 
print(t[1:, 2:].dim())
print('-----------------------')
print(t[1:, 1:]) # 1번부터 끝행까지 중, 1번부터 끝열까지
print(t[1:, 1:].size())
print(t[1:, 1:].dim())
print('-----------------------')
print(t[1, :]) # 1번 행의 모든 열
print(t[1, :].size())
print(t[1, :].dim())

NameError: name 't' is not defined

### Broadcasting

In [81]:
# Same shape

m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)
print(m1.size())
print(m2.size())

tensor([[5., 5.]])
torch.Size([1, 2])
torch.Size([1, 2])


In [84]:
# Vector + scalar

m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])   # > [[3,.3]]
print(m1 + m2)
print(m1.size())
print(m2.size())

tensor([[4., 5.]])
torch.Size([1, 2])
torch.Size([1])


In [95]:
# 2 x 1 Vector + 1 x 2 Vector

m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]]) # > [[3, 3], [4, 4]] 
print(m1 + m2)
print(m1.size())
print(m2.size())

tensor([[4., 5.],
        [5., 6.]])
torch.Size([1, 2])
torch.Size([2, 1])


In [94]:
m2 = torch.FloatTensor([[3], [4]])
print(m1)
print(m2)

tensor([[1., 2.]])
tensor([[3.],
        [4.]])


### Multiplication vs Matrix Multiplication

In [110]:

print('**********Matmul**********') # 매트릭스 곱하기(Matrix Multiplication)
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape )
print('Shape of Matrix 2: ', m2.shape )
print(m1.matmul(m2))

print()
print('***********Mul***********') #산술연산(Element-wise Multiplication)

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape )
print('Shape of Matrix 2: ', m2.shape )
print(m1 * m2)
print(m1.mul(m2))

**********Matmul**********
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])

***********Mul***********
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Mean

In [112]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [114]:
t = torch.LongTensor([1, 2])  # integers 값에 대해 mean값을 구할 수 없음.
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [116]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())
print(t.mean(dim=0)) # 열방향으로 평균
print(t.mean(dim=1)) # 행방향으로 평균
print(t.mean(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [119]:
t = torch.FloatTensor([[1., 2., 3.,], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)
print(t.mean())
print(t.mean(dim=0)) # 열방향으로 평균, 열 수 만큼 출력
print(t.mean(dim=1)) # 행방향으로 평균, 행 수 만큼 출력
print(t.mean(dim=-1)) # dim=1 과 동일

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor(6.5000)
tensor([5.5000, 6.5000, 7.5000])
tensor([ 2.,  5.,  8., 11.])
tensor([ 2.,  5.,  8., 11.])


### Sum

In [121]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [134]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

t = m1 + m2
print(t)
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))

print('---------------------------')
print(m2.mean())
print(m2)
print(m2.mean(dim=1))
print(m2.mean(dim=0))

tensor([[2., 3.],
        [5., 6.]])
tensor(4.)
tensor([3.5000, 4.5000])
tensor([2.5000, 5.5000])
---------------------------
tensor(1.5000)
tensor([[1.],
        [2.]])
tensor([1., 2.])
tensor([1.5000])


### Max and Argmax

In [136]:
t = torch.FloatTensor([[1,2], [3, 4]])
print(t.max())

tensor(4.)


In [139]:
print(t.max(dim=0)) # 열로 봤을때, 1, 3 중 3, 2, 4 중 4가 max값
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1]) # 위치 인덱스

(tensor([3., 4.]), tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [151]:
print(t.max(dim=1))
print(t.max(dim=-1))

(tensor([2., 4.]), tensor([1, 1]))
(tensor([2., 4.]), tensor([1, 1]))


### View (Reshape) : 디멘션 설정

In [158]:
t = np.array([[[0, 1, 2],
              [3, 4, 5]],
            
              [[6, 7, 8],
              [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft)
print(ft.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


In [179]:
print(ft.view([-1, 3])) # -1을 넣으면 알아서 위치를 맞춰줌.
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [157]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [168]:
print(ft.view([3, -1]))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


### Squeeze / Unsqueeze

- Squeeze : 군더더기를 제거함 A x 1 X B X C X 1 X D == > A X B X C X D
- Unsqueeze: 지정된 위치에 삽입

In [180]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [181]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [182]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [184]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [185]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [191]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [187]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Type Casting

In [201]:
lt = torch.LongTensor([1, 2, 3, 4]) # 정수
print(lt)

tensor([1, 2, 3, 4])


In [202]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [204]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenate

In [208]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(x, y)
print(torch.cat([x, y], dim=0))  # 4 x 2
print(torch.cat([x, y], dim=1))  # 2 x 4

tensor([[1., 2.],
        [3., 4.]]) tensor([[5., 6.],
        [7., 8.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking : 디멘션 사이즈가 같아야 한다는 제약사항이 있음.

In [209]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [210]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Ones and Zeros

In [214]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

print('-----------------------------------')

print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
-----------------------------------
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation

In [213]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.))
print(x)

print('-----------------------------------')

print(x.mul_(2.)) # 연산을 한 후 x에 저장
print(x) # 연산된 x가 출력됨.

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
-----------------------------------
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
