- 합계: print(t.sum(dim=1))
- 평균: print(t.mean(dim=0))


- 매트릭스 곱: print(m1.matmul(m2))
- 매트릭스 산술연산: print(m1.mul(m2) = print(m1 * m2)


- 최대값 : print(t.max(dim=0))
- 최대값 위치: print(t.max(dim=0)[1])


- reshape(디멘션설정): print(ft.view([-1, 3]).shape) / print(ft.view([-1, 1, 3]))
- print(ft.squeeze()) torch.size[3, 1] > [3]
- print(ft.unsqueeze(0)) torch.size[3] > [1, 3] # 0 == 인덱스


- 정수: lt = torch.LongTensor([1, 2, 3, 4])
- 실수: print(lt.float())
- Bool: bt = torch.ByteTensor([True, False, False, True])

- Concatenate: print(torch.cat([x, y], dim=0)) 4x2 / 2x4 만들기
- Staking: print(torch.stack([x, y, z], dim=1))


- 1로 초기화: print(torch.ones_like(x))
- 0으로 초기화: print(torch.zeros_like(x))
- 연산 저장: print(x.mul_(2.)) # 연산을 한 후 x에 저장

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    hypothesis = x_train * W + b
    
    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

# Linear Regression

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)


class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)
    
model = LinearRegressionModel()

# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])
# 모델 초기화
model = LinearRegressionModel()
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=0.01)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    prediction = model(x_train)
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train)
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 100번마다 로그 출력
    if epoch % 100 == 0:
        params = list(model.parameters())
        W = params[0].item()
        b = params[1].item()
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W, b, cost.item()
        ))

Epoch    0/1000 W: -0.101, b: 0.508 Cost: 4.630286
Epoch  100/1000 W: 0.713, b: 0.653 Cost: 0.061555
Epoch  200/1000 W: 0.774, b: 0.514 Cost: 0.038037
Epoch  300/1000 W: 0.822, b: 0.404 Cost: 0.023505
Epoch  400/1000 W: 0.860, b: 0.317 Cost: 0.014525
Epoch  500/1000 W: 0.890, b: 0.250 Cost: 0.008975
Epoch  600/1000 W: 0.914, b: 0.196 Cost: 0.005546
Epoch  700/1000 W: 0.932, b: 0.154 Cost: 0.003427
Epoch  800/1000 W: 0.947, b: 0.121 Cost: 0.002118
Epoch  900/1000 W: 0.958, b: 0.095 Cost: 0.001309
Epoch 1000/1000 W: 0.967, b: 0.075 Cost: 0.000809


# Multivariate Linear Regression

In [8]:
import torch.nn as nn
import torch.nn.functional as F

class MultivariateLinearRegressionModel(nn.Module):
    
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)
        
    def forward(self, x):
        return self.linear(x)
    
x_train = torch.FloatTensor([[73, 80, 75],
                            [93, 88, 93],
                            [89, 91, 90],
                            [96, 98, 100],
                            [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

model = MultivariateLinearRegressionModel()

optimizer = optim.SGD(model.parameters(), lr = 1e-5)


nb_epochs = 20
for epoch in range(nb_epochs + 1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
    epoch, nb_epochs, cost.item()
    ))

Epoch    0/20 Cost: 30778.531250
Epoch    1/20 Cost: 9655.531250
Epoch    2/20 Cost: 3034.586426
Epoch    3/20 Cost: 959.267456
Epoch    4/20 Cost: 308.761017
Epoch    5/20 Cost: 104.857498
Epoch    6/20 Cost: 40.940823
Epoch    7/20 Cost: 20.901897
Epoch    8/20 Cost: 14.616715
Epoch    9/20 Cost: 12.642475
Epoch   10/20 Cost: 12.019537
Epoch   11/20 Cost: 11.820096
Epoch   12/20 Cost: 11.753460
Epoch   13/20 Cost: 11.728462
Epoch   14/20 Cost: 11.716476
Epoch   15/20 Cost: 11.708610
Epoch   16/20 Cost: 11.702004
Epoch   17/20 Cost: 11.695824
Epoch   18/20 Cost: 11.689764
Epoch   19/20 Cost: 11.683700
Epoch   20/20 Cost: 11.677744


# 파일 불러오기

In [ ]:
import numpy as np
xy = np.loadtxt('C:/Users/student/Documents/PyTorch-master/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
print(x_data)
print(y_data)

print(x_data.shape) # x_data shape
print(len(x_data))  # x_data 길이
print(x_data[:5]) 

# Logistic Classification

In [9]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 4], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

W = torch.zeros((2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr =1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
        ))
        
# evaluation        
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
print(hypothesis[:5])

prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction[:4])
print(y_train[:4])

correct_prediction = prediction.float() == y_train
print(correct_prediction[:4])

Epoch    0/1000 Cost: 0.693147
Epoch  100/1000 Cost: 0.120070
Epoch  200/1000 Cost: 0.075141
Epoch  300/1000 Cost: 0.055294
Epoch  400/1000 Cost: 0.043913
Epoch  500/1000 Cost: 0.036476
Epoch  600/1000 Cost: 0.031216
Epoch  700/1000 Cost: 0.027291
Epoch  800/1000 Cost: 0.024248
Epoch  900/1000 Cost: 0.021817
Epoch 1000/1000 Cost: 0.019830
tensor([[0.0003],
        [0.0320],
        [0.0383],
        [0.9548],
        [0.9996]], grad_fn=<SliceBackward>)
tensor([[0],
        [0],
        [0],
        [1]], dtype=torch.uint8)
tensor([[0.],
        [0.],
        [0.],
        [1.]])
tensor([[1],
        [1],
        [1],
        [1]], dtype=torch.uint8)


# Class 만들어서 실행하기

In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
  
torch.manual_seed(1)

x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 4], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

W = torch.zeros((2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)  

class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
        return self.sigmoid(self.linear(x))
    
model = BinaryClassifier()

optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 100
for epoch in range(nb_epochs + 1):
    hypothesis = model(x_train)
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 10 == 0 :
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
               
        print('Epoch {:4d}/{} C ost: {:.6f} Accuracy {:2.2f}%'.format(
            epoch, nb_epochs, cost.item(), accuracy * 100
             ))

Epoch    0/100 Cost: 0.558251 Accuracy 83.33%
Epoch   10/100 Cost: 0.436861 Accuracy 83.33%
Epoch   20/100 Cost: 0.509068 Accuracy 66.67%
Epoch   30/100 Cost: 0.371135 Accuracy 83.33%
Epoch   40/100 Cost: 0.297522 Accuracy 83.33%
Epoch   50/100 Cost: 0.234258 Accuracy 100.00%
Epoch   60/100 Cost: 0.181100 Accuracy 100.00%
Epoch   70/100 Cost: 0.150244 Accuracy 100.00%
Epoch   80/100 Cost: 0.137193 Accuracy 100.00%
Epoch   90/100 Cost: 0.127950 Accuracy 100.00%
Epoch  100/100 Cost: 0.119988 Accuracy 100.00%


# 파일 로드하여 수행(diabetes)

In [14]:
import numpy as np
xy = np.loadtxt('C:/users/student/Documents/PyTorch-master/data-03-diabetes.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
x_train = torch.FloatTensor(x_data[:600])
y_train = torch.FloatTensor(y_data[:600])

x_test = torch.FloatTensor(x_data[600:])
y_test = torch.FloatTensor(y_data[600:])

# print(x_train[0:5])
# print(y_train[0:5])

W = torch.zeros((8, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W,b], lr =1)

nb_epochs = 100
for epoch in range(nb_epochs + 1):
    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 10 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()))
        
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
print(hypothesis[:5])

prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction[:5])

correct_prediction = prediction.float() == y_train
print(correct_prediction[:5])

accuracy = correct_prediction.sum().item() / len(correct_prediction)
print('Accuracy : {:2.2f}%'.format(accuracy * 100))

Epoch    0/100 Cost: 0.693146
Epoch   10/100 Cost: 0.570872
Epoch   20/100 Cost: 0.537613
Epoch   30/100 Cost: 0.517809
Epoch   40/100 Cost: 0.505164
Epoch   50/100 Cost: 0.496643
Epoch   60/100 Cost: 0.490663
Epoch   70/100 Cost: 0.486334
Epoch   80/100 Cost: 0.483123
Epoch   90/100 Cost: 0.480692
Epoch  100/100 Cost: 0.478822
tensor([[0.4322],
        [0.9238],
        [0.2422],
        [0.9439],
        [0.1637]], grad_fn=<SliceBackward>)
tensor([[0],
        [1],
        [0],
        [1],
        [0]], dtype=torch.uint8)
tensor([[1],
        [1],
        [1],
        [1],
        [1]], dtype=torch.uint8)
Accuracy : 77.17%


# Softmax classification

In [16]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


torch.manual_seed(1)

class softmaxClassifierModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(4, 3)
        
    def forward(self, x):
        return self.linear(x)
    
model = softmaxClassifierModel()

x_train = [[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]]
y_train = [2, 2, 2, 1, 1, 1, 0, 0]
x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

W = torch.zeros((4, 3), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD(model.parameters(), lr= 0.1)

# nb_epochs = 1000
# for epoch in range(nb_epochs + 1):
#     hypothesis = F.softmax(x_train.matmul(W) + b, dim=1) # or .mm or @
#     y_one_hot = torch.zeros_like(hypothesis)
#     y_one_hot.scatter_(1, y_train.unsqueeze(1), 1)
#     cost = (y_one_hot * -torch.log(F.softmax(hypothesis, dim=1))).sum(dim=1).mean()


nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    prediction = model(x_train)
    cost= F.cross_entropy(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 ==0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
        ))
print(cost.mean())


Epoch    0/1000 Cost: 1.616785
Epoch  100/1000 Cost: 0.658891
Epoch  200/1000 Cost: 0.573443
Epoch  300/1000 Cost: 0.518151
Epoch  400/1000 Cost: 0.473266
Epoch  500/1000 Cost: 0.433516
Epoch  600/1000 Cost: 0.396563
Epoch  700/1000 Cost: 0.360914
Epoch  800/1000 Cost: 0.325392
Epoch  900/1000 Cost: 0.289178
Epoch 1000/1000 Cost: 0.254148
tensor(0.2541, grad_fn=<MeanBackward1>)
